version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: gold-resource-mariadb
    ports:
      - ${DB_PORT_RESOURCE}:${DB_PORT}
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb-vl:/var/lib/mariadb

volumes:
  mariadb-vl:
    driver: local
