version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: gold-auth-mariadb
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb-vl:/var/lib/mariadb
  redis:
    image: redis:latest
    container_name: gold-auth-redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
  
  # 테스트용
  mariadb-test:
    image: mariadb:latest
    container_name: gold-auth-mariadb-test
    ports:
      - ${DB_TEST_PORT}:${DB_PORT}
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}_test
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb-test-vl:/var/lib/mariadb

volumes:
  mariadb-vl:
    driver: local
  mariadb-test-vl:
    driver: local
